<?php

namespace App\Repository;

use App\Entity\Generation;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Generation>
 */
class GenerationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Generation::class);
    }

    /**
     * Count PDF generated by user on a specific date
     * This is used to enforce subscription limits
     *
     * @param int $userId
     * @param \DateTime $startOfDay
     * @param \DateTime $endOfDay
     * @return int
     */
    public function countPdfGeneratedByUserOnDate(int $userId, \DateTime $startOfDay, \DateTime $endOfDay): int
    {
        return (int) $this->createQueryBuilder('g')
            ->select('COUNT(g.id)')
            ->where('g.user = :userId')
            ->andWhere('g.createdAt BETWEEN :startOfDay AND :endOfDay')
            ->setParameter('userId', $userId)
            ->setParameter('startOfDay', $startOfDay)
            ->setParameter('endOfDay', $endOfDay)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Find all generations for a user, ordered by most recent
     *
     * @param int $userId
     * @return Generation[]
     */
    public function findByUserOrderedByDate(int $userId): array
    {
        return $this->createQueryBuilder('g')
            ->where('g.user = :userId')
            ->setParameter('userId', $userId)
            ->orderBy('g.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Find generations by user with pagination
     *
     * @param int $userId
     * @param int $limit
     * @param int $offset
     * @return Generation[]
     */
    public function findByUserPaginated(int $userId, int $limit = 10, int $offset = 0): array
    {
        return $this->createQueryBuilder('g')
            ->where('g.user = :userId')
            ->setParameter('userId', $userId)
            ->orderBy('g.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getQuery()
            ->getResult();
    }
}
