parameters:
    app.supported_locales: 'fr|en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GotenbergService:
        arguments:
            $gotenbergUrl: '%env(GOTENBERG_URL)%'

when@dev:
    framework:
        profiler:
            only_exceptions: false

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true
